language: node_js
node_js:
  - node
deploy:
  provider: npm
  email: lxldevtest@163.com
  skip_cleanup: true
  api_key:
    secure: YlegOOyt46itY9CmML/IAtYYm7eCrEUjpAIG36FCpM/6dC5IR/bJGwGb9+v9jNob/bFLg+Q+OCjbnWN2Vl4siUufm1yc1hyWSrIbDKMhe3jnD2nUkM7ebQnmU5vEx5fgZA1/9yU8mkJCJJ7ZQXKYP49WrzYseDvpJknEpObjFlE1gznQAAuCH9lYP+SAWkSZRr4oFPH1cdis942Fha/LP9znRBhht0hPk/OJypQCRk4twSIAuTzY7Y/9Zujh1AILSa52GFMOgWkhFx7EZmIaqJbUKAmR3BHOg4fXcjTojRHX03UZslzHvXkmlAl+dd8yyOXlcDPYwfHDLYdcXJvP562g6VkNY/SYQ9dfS/zTBEDOhYCxjsN4phfRFE7NrHOaTW3YvZX1E06Nru+fFUybnO6onvR1un1wTrX4+/weZ+d6D8ouPyVbnz6O54NttgkdzsDhh1pmhKABj8d3t/uO8deWA/p6iEx2ye/9bcjGC4PcRkTzdA7Zh8WCxVgvHqplVGPlIo4qtBvERXVmSFkyOPwxpzzm7kvbQoiuKRdi4045kt8GbzO8mWOeaPciqCvx5gF2vAeQ4fWV8FOAEW8zt37ydPq9GzfQxFpFa9cil+Kcjih/+6I5raXy+MLCOD1Y7LpTQ7HY0QNrXyTKpy6J9n/8/LpHKj5VWN0ligoQGyQ=
  on:
    tags: true
